# Generated by Django 6.0.3 on 2026-03-20 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedobject',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='scenes.uploadedscene'),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='x1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='x2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='y1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detectedobject',
            name='y2',
            field=models.FloatField(default=0),
        ),
    ]
