# Generated by Django 6.0.3 on 2026-03-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('chair', 'Chair'), ('sofa', 'Sofa'), ('bed', 'Bed'), ('table', 'Table'), ('lamp', 'Lamp'), ('pillow', 'Pillow'), ('frame', 'Frame')], max_length=50),
        ),
    ]
